export const FOOD_FEED_ITEMS = [
  {
    id: 'dish-1',
    name: 'Truffle Smash Cheeseburger',
    restaurant: 'Smash & Sizzle Craft Burgers',
    price: 14.50,
    calories: 780,
    distance: '0.6 mi away',
    rating: 4.9,
    reviewsCount: 420,
    description: 'Double prime Angus patties, black truffle aioli, aged sharp cheddar on toasted brioche.',
    image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=1200&q=80',
    address: '142 S Market St',
    cuisine: 'American · Burgers',
    openHours: 'Open now · 11:00 AM - 10:00 PM',
    doordashUrl: 'https://www.doordash.com/search/store/smash%20burger',
  },
  {
    id: 'dish-2',
    name: 'Hot Honey & Burrata Artisan Pizza',
    restaurant: 'Fire & Stone Neapolitan Pizzeria',
    price: 18.00,
    calories: 920,
    distance: '1.1 mi away',
    rating: 4.8,
    reviewsCount: 680,
    description: 'San Marzano tomatoes, fresh cream burrata, spicy Calabrian chili honey, fresh basil.',
    image: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=1200&q=80',
    address: '88 Italian Alley',
    cuisine: 'Italian · Pizza',
    openHours: 'Open now · 12:00 PM - 11:00 PM',
    doordashUrl: 'https://www.doordash.com/search/store/pizza',
  },
  {
    id: 'dish-3',
    name: 'Black Garlic Tonkotsu Ramen',
    restaurant: 'Ramen Ichiko Bar',
    price: 16.25,
    calories: 640,
    distance: '0.8 mi away',
    rating: 4.9,
    reviewsCount: 890,
    description: '18-hour simmered rich pork broth, roasted black garlic oil, chashu pork belly, ramen egg.',
    image: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?auto=format&fit=crop&w=1200&q=80',
    address: '304 Japantown Plaza',
    cuisine: 'Japanese · Ramen',
    openHours: 'Open now · 11:30 AM - 10:30 PM',
    doordashUrl: 'https://www.doordash.com/search/store/ramen',
  },
  {
    id: 'dish-4',
    name: 'Korean Gochujang Crispy Wings',
    restaurant: 'Seoul Street Bites',
    price: 13.99,
    calories: 590,
    distance: '1.4 mi away',
    rating: 4.7,
    reviewsCount: 310,
    description: 'Double-fried extra crispy wings tossed in sweet and spicy gochujang chili glaze with sesame.',
    image: 'https://images.unsplash.com/photo-1567620832903-9fc6debc209f?auto=format&fit=crop&w=1200&q=80',
    address: '512 K-Town Blvd',
    cuisine: 'Korean · Street Food',
    openHours: 'Open now · 4:00 PM - 12:00 AM',
    doordashUrl: 'https://www.doordash.com/search/store/korean%20wings',
  },
  {
    id: 'dish-5',
    name: 'Birria De Res Quesatacos (3pc)',
    restaurant: 'La Taqueria Del Sol',
    price: 15.50,
    calories: 710,
    distance: '0.4 mi away',
    rating: 4.9,
    reviewsCount: 1120,
    description: 'Slow-braised beef brisket folded in crisp corn tortillas with melted Oaxaca cheese and consommé.',
    image: 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?auto=format&fit=crop&w=1200&q=80',
    address: '77 Mission Ave',
    cuisine: 'Mexican · Tacos',
    openHours: 'Open now · 10:00 AM - 11:00 PM',
    doordashUrl: 'https://www.doordash.com/search/store/birria%20tacos',
  }
];